### ISSUE TITLE
some question about dataset

### ISSUE THREAD

**Issue by grdiv** [wonje-Jang/github_SeRMdataset#1]
When I reproduced the results, I encountered some problems:
1. What are the camera intrinsic?
2. Could you provide the mapping relationship between pixel gray value and category?  

Much appreciated.

**Comment by SeRM-dataset** [comment]
Hello.
This is Wonje Jang.

1. It is not possible to provide information on camera intrinsic
parameters.
However, we will provide the data used for calibration sooner or later so
that you can guess the intrinsic parameters.
Thanks for the good point.

2. Information about labels is newly uploaded to GitHub (
https://github.com/SeRM-dataset/dataset/datasetInfo.md).

Best Regards
Sincerely,
Wonje Jang



*JANG WONJEComputational Intelligence Lab.*School of Electrical &
Electronic Engineering,
Yonsei University, Korea
E-mail : ***@***.***
Cell : +82 10-8630-8683
Office : +82 2-2123-7729


2022년 12월 27일 (화) 오후 8:13, grdiv ***@***.***>님이 작성:
